//+build !headless

package ebiten

import (
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/split-cube-studios/ardent/engine"
)

var toEbitenKey = map[int]ebiten.Key{
	engine.Key0:            ebiten.Key0,
	engine.Key1:            ebiten.Key1,
	engine.Key2:            ebiten.Key2,
	engine.Key3:            ebiten.Key3,
	engine.Key4:            ebiten.Key4,
	engine.Key5:            ebiten.Key5,
	engine.Key6:            ebiten.Key6,
	engine.Key7:            ebiten.Key7,
	engine.Key8:            ebiten.Key8,
	engine.Key9:            ebiten.Key9,
	engine.KeyA:            ebiten.KeyA,
	engine.KeyB:            ebiten.KeyB,
	engine.KeyC:            ebiten.KeyC,
	engine.KeyD:            ebiten.KeyD,
	engine.KeyE:            ebiten.KeyE,
	engine.KeyF:            ebiten.KeyF,
	engine.KeyG:            ebiten.KeyG,
	engine.KeyH:            ebiten.KeyH,
	engine.KeyI:            ebiten.KeyI,
	engine.KeyJ:            ebiten.KeyJ,
	engine.KeyK:            ebiten.KeyK,
	engine.KeyL:            ebiten.KeyL,
	engine.KeyM:            ebiten.KeyM,
	engine.KeyN:            ebiten.KeyN,
	engine.KeyO:            ebiten.KeyO,
	engine.KeyP:            ebiten.KeyP,
	engine.KeyQ:            ebiten.KeyQ,
	engine.KeyR:            ebiten.KeyR,
	engine.KeyS:            ebiten.KeyS,
	engine.KeyT:            ebiten.KeyT,
	engine.KeyU:            ebiten.KeyU,
	engine.KeyV:            ebiten.KeyV,
	engine.KeyW:            ebiten.KeyW,
	engine.KeyX:            ebiten.KeyX,
	engine.KeyY:            ebiten.KeyY,
	engine.KeyZ:            ebiten.KeyZ,
	engine.KeyApostrophe:   ebiten.KeyApostrophe,
	engine.KeyBackslash:    ebiten.KeyBackslash,
	engine.KeyBackspace:    ebiten.KeyBackspace,
	engine.KeyCapsLock:     ebiten.KeyCapsLock,
	engine.KeyComma:        ebiten.KeyComma,
	engine.KeyDelete:       ebiten.KeyDelete,
	engine.KeyDown:         ebiten.KeyDown,
	engine.KeyEnd:          ebiten.KeyEnd,
	engine.KeyEnter:        ebiten.KeyEnter,
	engine.KeyEqual:        ebiten.KeyEqual,
	engine.KeyEscape:       ebiten.KeyEscape,
	engine.KeyF1:           ebiten.KeyF1,
	engine.KeyF2:           ebiten.KeyF2,
	engine.KeyF3:           ebiten.KeyF3,
	engine.KeyF4:           ebiten.KeyF4,
	engine.KeyF5:           ebiten.KeyF5,
	engine.KeyF6:           ebiten.KeyF6,
	engine.KeyF7:           ebiten.KeyF7,
	engine.KeyF8:           ebiten.KeyF8,
	engine.KeyF9:           ebiten.KeyF9,
	engine.KeyF10:          ebiten.KeyF10,
	engine.KeyF11:          ebiten.KeyF11,
	engine.KeyF12:          ebiten.KeyF12,
	engine.KeyGraveAccent:  ebiten.KeyGraveAccent,
	engine.KeyHome:         ebiten.KeyHome,
	engine.KeyInsert:       ebiten.KeyInsert,
	engine.KeyKP0:          ebiten.KeyKP0,
	engine.KeyKP1:          ebiten.KeyKP1,
	engine.KeyKP2:          ebiten.KeyKP2,
	engine.KeyKP3:          ebiten.KeyKP3,
	engine.KeyKP4:          ebiten.KeyKP4,
	engine.KeyKP5:          ebiten.KeyKP5,
	engine.KeyKP6:          ebiten.KeyKP6,
	engine.KeyKP7:          ebiten.KeyKP7,
	engine.KeyKP8:          ebiten.KeyKP8,
	engine.KeyKP9:          ebiten.KeyKP9,
	engine.KeyKPAdd:        ebiten.KeyKPAdd,
	engine.KeyKPDecimal:    ebiten.KeyKPDecimal,
	engine.KeyKPDivide:     ebiten.KeyKPDivide,
	engine.KeyKPEnter:      ebiten.KeyKPEnter,
	engine.KeyKPEqual:      ebiten.KeyKPEqual,
	engine.KeyKPMultiply:   ebiten.KeyKPMultiply,
	engine.KeyKPSubtract:   ebiten.KeyKPSubtract,
	engine.KeyLeft:         ebiten.KeyLeft,
	engine.KeyLeftBracket:  ebiten.KeyLeftBracket,
	engine.KeyMenu:         ebiten.KeyMenu,
	engine.KeyMinus:        ebiten.KeyMinus,
	engine.KeyNumLock:      ebiten.KeyNumLock,
	engine.KeyPageDown:     ebiten.KeyPageDown,
	engine.KeyPageUp:       ebiten.KeyPageUp,
	engine.KeyPause:        ebiten.KeyPause,
	engine.KeyPeriod:       ebiten.KeyPeriod,
	engine.KeyPrintScreen:  ebiten.KeyPrintScreen,
	engine.KeyRight:        ebiten.KeyRight,
	engine.KeyRightBracket: ebiten.KeyRightBracket,
	engine.KeyScrollLock:   ebiten.KeyScrollLock,
	engine.KeySemicolon:    ebiten.KeySemicolon,
	engine.KeySlash:        ebiten.KeySlash,
	engine.KeySpace:        ebiten.KeySpace,
	engine.KeyTab:          ebiten.KeyTab,
	engine.KeyUp:           ebiten.KeyUp,
	engine.KeyAlt:          ebiten.KeyAlt,
	engine.KeyControl:      ebiten.KeyControl,
	engine.KeyShift:        ebiten.KeyShift,
}

var toEbitenMouseButton = map[int]ebiten.MouseButton{
	engine.MouseButtonLeft:   ebiten.MouseButtonLeft,
	engine.MouseButtonRight:  ebiten.MouseButtonRight,
	engine.MouseButtonMiddle: ebiten.MouseButtonMiddle,
}
